cmake -B build -G Ninja \
 -DENABLE_LTO=OFF \
 -DENABLE_X11=OFF \
 -DLIBRETRO=OFF \
 -DENABLE_NOGUI=OFF \
 -DENABLE_QT=OFF \
 -DENABLE_TESTS=OFF \
 -DENABLE_EGL=ON \
 -DTHREADS_PTHREAD_ARG=OFF \
 -DUSE_DISCORD_PRESENCE=OFF \
 -DBUILD_SHARED_LIBS=OFF \
 -DCMAKE_BUILD_TYPE=Release
ninja -C build

